version: "3"

services:
  backend:
    env_file: "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "raytan42/tweetsis-backend"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "raytan42/tweetsis-frontend"
    ports:
      - "3000:3000"
    links:
      - backend
